/*
 * SPDX-FileCopyrightText: 2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _USE_MATH_DEFINES
#define _USE_MATH_DEFINES
#endif
//#include <common/common.h>
//#include "llama.h"
#include "Llama2Device.h"
#include <fstream>
#include <yarp/os/LogComponent.h>
#include <yarp/os/LogStream.h>
#include <yarp/os/ResourceFinder.h>

#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

using namespace yarp::os;
using namespace yarp::dev;

YARP_LOG_COMPONENT(LLAMA2DEVICE, "yarp.llama2Device", yarp::os::Log::TraceType);


Llama2Device::Llama2Device()
{

}

bool Llama2Device::open(yarp::os::Searchable &config)
{
    if (!parseParams(config))  { return false; }
    // use if want to run with gemma
    // m_model_name = "/home/leonardo/Repos/yarp-device-llama2/models/gemma/gemma-2b-it.gguf";
    // initialize LLM
    init_LLM(m_model_name);

    return true;
}

// method for the initialization of the LLM model
bool Llama2Device::init_LLM(const std::string &model_path)
{
    // number of layers to offload to the GPU
    ngl = 99;
    // number of tokens to predict
    n_predict = 64;
    // initialize the model
    model_params = llama_model_default_params();
    model_params.n_gpu_layers = ngl;

    model = llama_load_model_from_file(m_model_name.c_str(), model_params);

    // check if model is found, if not return an error message
    if (model == NULL){
        yCError(LLAMA2DEVICE) << "Error: unable to find model!";
        return false;
    }
    else{
        yCInfo(LLAMA2DEVICE) << "Model correctly intialized";
    }

    return true;
}

bool Llama2Device::ask(const std::string &question, yarp::dev::LLM_Message &oAnswer)
{
    model_question = question;
    // if prompt is set, add it to the question
    if(prompt_set == true){
        model_question += " " + m_prompt.content;
    }

    // add question to the conversation
    yarp::dev::LLM_Message message;
    message.type = "user";
    message.content = question;
    m_conversation.push_back(message);

    // variable used to store the complete answer generated by the model
    std::string final_output;

    // tokenize the prompt
    // find the number of tokens in the prompt
    const int n_prompt = -llama_tokenize(model, model_question.c_str(), model_question.size(), NULL, 0, true, true);
    // allocate space for the tokens and tokenize the prompt
    std::vector<llama_token> prompt_tokens(n_prompt);
    if(llama_tokenize(model, model_question.c_str(), model_question.size(), prompt_tokens.data(), prompt_tokens.size(), true, true) < 0){
        yCError(LLAMA2DEVICE) << "Error: failed to tokenize the prompt";
        return false;
    }
    else{
        yCInfo(LLAMA2DEVICE) << "Prompt tokenized correctly";
    }

    // initialize the context
    llama_context_params ctx_params = llama_context_default_params();
    // n_ctx is the context size
    ctx_params.n_ctx = n_prompt + n_predict -1;
    // n_batch is the maximum number of tokens that can be processed in a single call to llama_decode
    ctx_params.n_batch = n_prompt;
    // enable performance counters
    ctx_params.no_perf = false;

    llama_context * ctx = llama_new_context_with_model(model, ctx_params);

    // check if context has been initialized correctly
    if(ctx == NULL){
        yCError(LLAMA2DEVICE) << "Error: failed to create the llama_context";
        return false;
    }
    else{
        yCInfo(LLAMA2DEVICE) << "Context correctly initialized";
    }

    // initialize the sampler
    auto sparams = llama_sampler_chain_default_params();
    sparams.no_perf = false;
    llama_sampler * smpl = llama_sampler_chain_init(sparams);

    llama_sampler_chain_add(smpl, llama_sampler_init_greedy());

    //print the prompt token by token
    for(auto id: prompt_tokens){
        char buf[128];
        int n = llama_token_to_piece(model, id, buf, sizeof(buf), 0, true);
        if(n < 0){
            yCError(LLAMA2DEVICE) << "Error: failed to convert token to piece";
            return false;
        }
    }

    // prepare a batch for the prompt
    llama_batch batch = llama_batch_get_one(prompt_tokens.data(), prompt_tokens.size());

    // main loop
    const auto t_main_start = ggml_time_us();
    int n_decode = 0;
    llama_token new_token_id;

    for (int n_pos = 0; n_pos + batch.n_tokens < n_prompt + n_predict;) {
        // evaluate the current batch with the transformer model
        if(llama_decode(ctx, batch)){
            yCError(LLAMA2DEVICE) << "Error: failed to eval";
            return false;
        }

        n_pos += batch.n_tokens;

        // sample the next token
        {
            new_token_id = llama_sampler_sample(smpl, ctx, -1);

            // check if it is the end of a generation
            if(llama_token_is_eog(model, new_token_id)){
                break;
            }

            char buf[128];
            int n = llama_token_to_piece(model, new_token_id, buf, sizeof(buf), 0, true);
            if(n < 0){
                yCError(LLAMA2DEVICE) << "Error: failed to convert token to piece";
                return false;
            }

            // accumulate tokens
            final_output += std::string(buf, n);

            // prepare the next batch with the sampled token
            batch = llama_batch_get_one(&new_token_id, 1);

            n_decode += 1;

            // compute progress bar percentage
            int progress = static_cast<int>(100.0 * n_decode / n_predict);

            // print progress bar
            std::string progress_bar = "[";
            int bar_width = 50;  // progress bar length

            int pos = bar_width * progress / 100;
            for (int i = 0; i < bar_width; ++i) {
                if (i < pos) progress_bar += "=";
                else if (i == pos) progress_bar += ">";
                else progress_bar += " ";
            }
            progress_bar += "] " + std::to_string(progress) + "%";

            yCInfo(LLAMA2DEVICE) << progress_bar;
        }
    }

    yCInfo(LLAMA2DEVICE) << final_output;

    const auto t_main_end = ggml_time_us();

    // add model answer to the conversation 
    message.type = "assitant";
    message.content = final_output;
    m_conversation.push_back(message);

    // write model answer inside oAnswer
    oAnswer.type = "assistant";
    oAnswer.content = final_output;

    return true;
}


bool Llama2Device::setPrompt(const std::string &prompt)
{
    // check if a prompt is already set
    if(prompt_set == true){
        yCError(LLAMA2DEVICE)<< "A prompt is already set. You must delete conversation first";
        return true;
    }
    // if the prompt is not already set, set the prompt
    prompt_set = true;

    m_prompt.type = "System";
    m_prompt.content = prompt;

    // add prompt to the conversation
    yarp::dev::LLM_Message message;
    message.type = "prompt";
    message.content = prompt;
    m_conversation.push_back(message);
    
    return true;
}


bool Llama2Device::readPrompt(std::string &oPrompt)
{   
    // check if the prompt is set
    if(prompt_set == false){
        yCError(LLAMA2DEVICE) << "Prompt is not set";
        return true;
    }
    // if prompt is set, read it
    oPrompt = m_prompt.content;

    return true;
}


bool Llama2Device::getConversation(std::vector<yarp::dev::LLM_Message> &oConversation)
{
    // check if the conversation is empty
    if(m_conversation.empty()){
        yCInfo(LLAMA2DEVICE) << "The conversation is empty";
        return true;
    }

    // if the conversation is not empty, print it
    for (const auto& msg : oConversation) {
        yCInfo(LLAMA2DEVICE) << "Role: " << msg.type;
        yCInfo(LLAMA2DEVICE) << "Content: " << msg.content;
        yCInfo(LLAMA2DEVICE) << "-------------------";
    }
    
    // set the value of the conversation
    oConversation = m_conversation;
    return true;
}


bool Llama2Device::deleteConversation() noexcept
{
    // check if the conversation is empty
    if (m_conversation.empty()){
        yCInfo(LLAMA2DEVICE) << "Conversation is already empty";
        return true;
    }
    // if not empty, clear the conversation
    m_conversation.clear();
    prompt_set = false;

    yCInfo(LLAMA2DEVICE) << "Conversation deleted";
    return true;
}

bool Llama2Device::refreshConversation() noexcept
{
    return true;
}

bool Llama2Device::close()
{
    yCInfo(LLAMA2DEVICE) << "Closing";
    return true;
}

void Llama2Device::help() {
    std::cout << "Llama2Device Methods:" << std::endl;
    std::cout << "1. setPrompt" << std::endl;
    std::cout << "   - Set the initial prompt for the model." << std::endl;
    std::cout << "2. ask" << std::endl;
    std::cout << "   - Ask a question to the model and get an answer." << std::endl;
    std::cout << "3. getConversation" << std::endl;
    std::cout << "   - Prints the current conversation with the model." << std::endl;
    std::cout << "4. deleteConversation" << std::endl;
    std::cout << "   - Deletes the current conversation" << std::endl;
    std::cout << "5. readPrompt" << std::endl;
    std::cout << "   - Prints the last prompt provided to the model" << std::endl;
    std::cout << "6. help" << std::endl;
    std::cout << "   - Prints the list of possible commands and their description." << std::endl;
}
