/*
 * SPDX-FileCopyrightText: 2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _USE_MATH_DEFINES
#define _USE_MATH_DEFINES
#endif

#include "llama.h"
#include "Llama2Device.h"
#include <fstream>
#include <yarp/os/LogComponent.h>
#include <yarp/os/LogStream.h>
#include <yarp/os/ResourceFinder.h>
#include "common.h"
#include "arg.h"
#include "sampling.h"

#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

#include "Utils.h"

using namespace yarp::dev;

YARP_LOG_COMPONENT(LLAMA2DEVICE, "yarp.llama2Device", yarp::os::Log::TraceType);

Llama2Device::Llama2Device()
{

}

bool Llama2Device::open(yarp::os::Searchable &config)
{
    if (!parseParams(config))  { return false; }
    // initialize LLM
    std::string model_path;
    bool has_model_context{m_model_context != ""};
    yarp::os::ResourceFinder resource_finder;
    if(has_model_context)
    {
        resource_finder.setDefaultContext(m_model_context);
        model_path = resource_finder.findFile(m_model_name);
    }
    else
    {
        model_path = m_model_name;
    }
    init_LLM(model_path);
    bool has_prompt_file{m_prompt_file != ""};
    bool has_prompt_context{m_prompt_context != ""};
    if(has_prompt_context)
    {
        resource_finder.setDefaultContext(m_prompt_context);
    }

    if(has_prompt_file)
    {
        std::string prompt_file_fullpath = resource_finder.findFile(m_prompt_file);
        auto stream = std::ifstream(prompt_file_fullpath);
        if (!stream)
        {
            yCWarning(LLAMA2DEVICE) << "File:" << prompt_file_fullpath << "does not exist or path is invalid";
        }
        else
        {
            std::ostringstream sstr;
            sstr << stream.rdbuf(); //Reads the entire file into the stringstream
            if(!setPrompt(sstr.str()))
            {
                return false;
            }
        }
    }

    return true;
}

// method for the initialization of the LLM model
yarp::dev::ReturnValue Llama2Device::init_LLM(const std::string &model_path)
{
    // start llama-server in background
    startLlama2Server(model_path, m_context, m_ngl);

    return yarp::dev::ReturnValue::return_code::return_value_ok;
}

yarp::dev::ReturnValue Llama2Device::ask(const std::string &question, yarp::dev::LLM_Message &oAnswer)
{
    nlohmann::json request_json;
    request_json["model"] = "default";
    request_json["max_tokens"] = m_npredict;

    // Pass the conversation to the model
    nlohmann::json messages_array = nlohmann::json::array();
    for (const auto& msg : m_conversation) {
        messages_array.push_back({{"role", msg.type}, {"content", msg.content}});
    }

    // Add new question to the conversation
    messages_array.push_back({{"role", "user"}, {"content", question}});

    // Insert array messages into the request
    request_json["messages"] = messages_array;

    // Convert JSON to string and send the request to the model
    std::string risposta = sendPostRequest(request_json.dump());

    // extract model's answer
    std::string final_output = extractContent(risposta);

    // add question to the conversation
    yarp::dev::LLM_Message message;
    message.type = "user";
    message.content = question;
    m_conversation.push_back(message);

    // variable used to store the complete answer generated by the model
    final_output = extractContent(risposta);

    // add model answer to the conversation
    message.type = "assitant";
    message.content = final_output;
    m_conversation.push_back(message);

    // write model answer inside oAnswer
    oAnswer.type = "assistant";
    oAnswer.content = final_output;

    return yarp::dev::ReturnValue::return_code::return_value_ok;
}


yarp::dev::ReturnValue Llama2Device::setPrompt(const std::string &prompt)
{
    // check if a prompt is already set
    if(prompt_set == true){
        yCError(LLAMA2DEVICE)<< "A prompt is already set. You must delete conversation first";
        return yarp::dev::ReturnValue::return_code::return_value_error_generic;
    }
    // if the prompt is not already set, set the prompt
    prompt_set = true;
    first_prompt_set = true;

    m_prompt.type = "system";
    m_prompt.content = prompt;

    // add prompt to the conversation
    yarp::dev::LLM_Message message;
    message.type = "system";
    message.content = prompt;
    m_conversation.push_back(message);

    return yarp::dev::ReturnValue::return_code::return_value_ok;
}


yarp::dev::ReturnValue Llama2Device::readPrompt(std::string &oPrompt)
{
    // check if the prompt is set
    if(prompt_set == false){
        yCError(LLAMA2DEVICE) << "Prompt is not set";
        return yarp::dev::ReturnValue::return_code::return_value_error_generic;
    }
    // if prompt is set, read it
    oPrompt = m_prompt.content;

    return yarp::dev::ReturnValue::return_code::return_value_ok;
}


yarp::dev::ReturnValue Llama2Device::getConversation(std::vector<yarp::dev::LLM_Message> &oConversation)
{
    // check if the conversation is empty
    if(m_conversation.empty()){
        yCInfo(LLAMA2DEVICE) << "The conversation is empty";
        return yarp::dev::ReturnValue::return_code::return_value_error_generic;
    }

    // if the conversation is not empty, print it
    for (const auto& msg : oConversation) {
        yCInfo(LLAMA2DEVICE) << "Role: " << msg.type;
        yCInfo(LLAMA2DEVICE) << "Content: " << msg.content;
        yCInfo(LLAMA2DEVICE) << "-------------------";
    }

    // set the value of the conversation
    oConversation = m_conversation;
    return yarp::dev::ReturnValue::return_code::return_value_ok;
}


yarp::dev::ReturnValue Llama2Device::deleteConversation() noexcept
{
    // check if the conversation is empty
    if (m_conversation.empty()){
        yCInfo(LLAMA2DEVICE) << "Conversation is already empty";
        return yarp::dev::ReturnValue::return_code::return_value_error_generic;
    }
    // if not empty, clear the conversation
    m_conversation.clear();
    prompt_set = false;
    first_prompt_set = false;

    yCInfo(LLAMA2DEVICE) << "Conversation deleted";
    return yarp::dev::ReturnValue::return_code::return_value_ok;
}

yarp::dev::ReturnValue Llama2Device::refreshConversation() noexcept
{
    return yarp::dev::ReturnValue::return_code::return_value_ok;
}

bool Llama2Device::close()
{
    yCInfo(LLAMA2DEVICE) << "Closing";
    return true;
}

void Llama2Device::help() {
    std::cout << "Llama2Device Methods:" << std::endl;
    std::cout << "1. setPrompt" << std::endl;
    std::cout << "   - Set the initial prompt for the model." << std::endl;
    std::cout << "2. ask" << std::endl;
    std::cout << "   - Ask a question to the model and get an answer." << std::endl;
    std::cout << "3. getConversation" << std::endl;
    std::cout << "   - Prints the current conversation with the model." << std::endl;
    std::cout << "4. deleteConversation" << std::endl;
    std::cout << "   - Deletes the current conversation" << std::endl;
    std::cout << "5. readPrompt" << std::endl;
    std::cout << "   - Prints the last prompt provided to the model" << std::endl;
    std::cout << "6. help" << std::endl;
    std::cout << "   - Prints the list of possible commands and their description." << std::endl;
}
